In [1]:
import pandas as pd
from funciones_estadisticos import *

In [2]:
book_submissions, book_comments = separar_dataframes('ejemplo_subreddit_books.json')
jobs_submissions, jobs_comments = separar_dataframes('ejemplo_subreddit_jobs.json')
lol_submissions, lol_comments = separar_dataframes('ejemplo_subreddit_LeagueOfLegends.json')
random_submissions, random_comments = separar_dataframes('ejemplo_subreddit_RandomThoughts.json')
travel_submissions, travel_comments = separar_dataframes('ejemplo_subreddit_travel.json')
unpopular_submissions, unpopular_comments = separar_dataframes('ejemplo_subreddit_unpopularopinion.json')

lista_dataframes = [book_submissions, book_comments, jobs_submissions, jobs_comments, lol_submissions, lol_comments,
					random_submissions, random_comments, travel_submissions, travel_comments, unpopular_submissions, unpopular_comments]

lista_dataframes_comentarios = [book_comments, jobs_comments, lol_comments, random_comments, travel_comments, unpopular_comments]

display(book_submissions)
display(book_comments)

,author,created_utc,id,name,num_comments,score,selftext,subreddit,title,created_datetime
0,cv5cv6,1.735728e+09,1hr0llg,t3_1hr0llg,161,3640,,books,It’s Public Domain Day. Copyright has expired ...,2025-01-01T10:43:05+00:00
1,FrancescoGozzo,1.735825e+09,1hrtvb7,t3_1hrtvb7,1537,400,If I have to think of a book for which I had h...,books,What's a book you were looking forward to read...,2025-01-02T13:38:13+00:00
2,EmpressPlotina,1.735924e+09,1hsr8kb,t3_1hsr8kb,176,22,"... but annoyingly, you end up DNF'ing or slog...",books,What are authors that you almost enjoy,2025-01-03T17:04:59+00:00
3,Hrmbee,1.736032e+09,1htr6og,t3_1htr6og,617,3138,,books,A Book App Used AI to ‘Roast’ Its Users. It We...,2025-01-04T23:10:38+00:00
4,AutoModerator,1.736161e+09,1huwikx,t3_1huwikx,1308,241,Hi everyone!\n\nWhat are you reading? What hav...,books,What Books did You Start or Finish Reading thi...,2025-01-06T11:00:10+00:00
...,...,...,...,...,...,...,...,...,...,...
65,AutoModerator,1.743682e+09,1jqgkke,t3_1jqgkke,191,1,"Welcome readers,\n\nMarch 31 was [Internationa...",books,Favorite Books with Transgender Characters: Ap...,2025-04-03T12:01:44+00:00
66,n10w4,1.743870e+09,1js6yc0,t3_1js6yc0,244,2528,A breakdown of books being removed for DEI pur...,books,We’re Committing Cultural Suicide,2025-04-05T16:12:10+00:00
67,AutoModerator,1.744020e+09,1jthm06,t3_1jthm06,702,115,Hi everyone!\n\nWhat are you reading? What hav...,books,What Books did You Start or Finish Reading thi...,2025-04-07T10:00:31+00:00
68,Wickersnap,1.744140e+09,1julzli,t3_1julzli,410,903,"...Or at least, female-presenting. \n\n\nI don...",books,I spent my entire first readthrough of All Sys...,2025-04-08T19:17:41+00:00
69,Sangwoosconfidant,1.744228e+09,1jvf39c,t3_1jvf39c,299,193,I know rating systems are kind of tricky topic...,books,"When it comes to reading, what is your persona...",2025-04-09T19:54:27+00:00

,author,body,controversiality,created_utc,id,link_id,parent_id,score,subreddit,created_datetime
0,cv5cv6,"A Farewell to Arms by Hemingway, Faulkner’s Th...",0,1.735728e+09,m4tz9ux,t3_1hr0llg,t3_1hr0llg,1017,books,2025-01-01T10:43:56+00:00
1,Ritamove18,Dumb question because I'm form Germany. Should...,0,1.735729e+09,m4u01j9,t3_1hr0llg,t3_1hr0llg,25,books,2025-01-01T10:52:32+00:00
2,cv5cv6,Not in the US. Copyright generally expires 95...,0,1.735729e+09,m4u0adp,t3_1hr0llg,t1_m4u01j9,69,books,2025-01-01T10:55:17+00:00
3,Ritamove18,Thank you! Very interesting.,0,1.735729e+09,m4u0gj5,t3_1hr0llg,t1_m4u0adp,7,books,2025-01-01T10:57:13+00:00
4,PragmaticTree,I'm glad these are out of copyright but I can'...,0,1.735731e+09,m4u35qp,t3_1hr0llg,t3_1hr0llg,270,books,2025-01-01T11:26:31+00:00
...,...,...,...,...,...,...,...,...,...,...
2095,LightGalaxyM31,"1: Hated it, or something gave me the ick\n2: ...",0,1.744230e+09,mm9vdna,t3_1jvf39c,t3_1jvf39c,1,books,2025-04-09T20:25:09+00:00
2096,dethb0y,"I only do 3 stars, really: \n\n1 - DNF, or so ...",0,1.744230e+09,mm9vovv,t3_1jvf39c,t3_1jvf39c,1,books,2025-04-09T20:26:39+00:00
2097,Uncanny--,I don't see a reason to hold out on making 5 s...,0,1.744230e+09,mm9vrro,t3_1jvf39c,t3_1jvf39c,2,books,2025-04-09T20:27:02+00:00
2098,Real-Definition-6431,"I’m binary as hell when it comes to books, eit...",0,1.744230e+09,mm9vu8d,t3_1jvf39c,t3_1jvf39c,3,books,2025-04-09T20:27:22+00:00
2099,MooshAro,"⭐️: Awful, didn't finish or didn't want to fin...",0,1.744230e+09,mm9vvnh,t3_1jvf39c,t3_1jvf39c,5,books,2025-04-09T20:27:33+00:00

In [3]:
histograma(lista_dataframes)

In [4]:
lista_dataframes_metricas = metricas_a_df(lista_dataframes_comentarios, 'body')

metricas_generales = calcular_estadisticos_corpus(lista_dataframes_metricas)

Calculando métricas para 2100 filas de r/books...
Calculando métricas para 2100 filas de r/jobs...
Calculando métricas para 2100 filas de r/leagueoflegends...
Calculando métricas para 2100 filas de r/RandomThoughts...
Calculando métricas para 2100 filas de r/travel...
Calculando métricas para 2100 filas de r/unpopularopinion...
✅ ¡Todas las métricas calculadas!

In [5]:
display(metricas_generales)

,Subreddit,Comentarios,Total Palabras,Total Tokens,Media Palabras/Coment.,Media Frases/Coment.,Riqueza Léxica Media (TTR %)
0,r/books,2100,78129,92692,37.20,2.67,87.63
1,r/travel,2100,69998,82178,33.33,2.62,88.91
2,r/jobs,2100,69838,81455,33.26,2.64,88.93
3,r/unpopularopinion,2100,60729,71339,28.92,2.34,89.48
4,r/leagueoflegends,2100,57209,65130,27.24,1.89,91.57
5,r/RandomThoughts,2100,34997,42655,16.67,1.73,92.96

In [9]:
boxplot(lista_dataframes_metricas, metrica='palabras')