In [1]:
import pandas as pd
from funciones_estadisticos import *

In [2]:
datos_submissions, datos_comments = separar_dataframes('ejemplo_subreddit_books.json')

display(datos_submissions)
display(datos_comments)

,_meta,all_awardings,allow_live_comments,approved_at_utc,approved_by,archived,author,author_flair_background_color,author_flair_css_class,author_flair_richtext,...,url,url_overridden_by_dest,user_reports,view_count,visited,wls,created_datetime,previous_selftext,author_cakeday,link_flair_template_id
0,{'retrieved_2nd_on': 1735973561},[],False,None,None,False,Roland_D_Sawyboy,NaN,NaN,[],...,https://slate.com/life/2025/01/reading-decline...,https://slate.com/life/2025/01/reading-decline...,[],None,False,6,2025-01-02T18:52:32+00:00,NaN,NaN,NaN
1,"{'is_edited': True, 'retrieved_2nd_on': 173605...",[],False,None,None,False,EmpressPlotina,NaN,NaN,[],...,https://www.reddit.com/r/books/comments/1hsr8k...,NaN,[],None,False,6,2025-01-03T17:04:59+00:00,"... but annoyingly, you end up DNF'ing or slog...",NaN,NaN
2,{'retrieved_2nd_on': 1736073765},[],False,None,None,False,sessna4009,NaN,NaN,[],...,https://www.reddit.com/r/books/comments/1hszaw...,NaN,[],None,False,6,2025-01-03T22:42:39+00:00,NaN,NaN,NaN
3,{'retrieved_2nd_on': 1736091175},[],False,None,None,False,marketrent,NaN,NaN,[],...,https://www.schoollibraryjournal.com/story/Jud...,https://www.schoollibraryjournal.com/story/Jud...,[],None,False,6,2025-01-04T03:32:48+00:00,NaN,NaN,NaN
4,"{'is_edited': True, 'retrieved_2nd_on': 173613...",[],False,None,None,False,smansaxx3,NaN,NaN,[],...,https://www.reddit.com/r/books/comments/1htfh8...,NaN,[],None,False,6,2025-01-04T14:28:02+00:00,I tried searching old posts and didn't find an...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,"{'is_edited': True, 'retrieved_2nd_on': 174318...",[],False,None,None,False,SeaAsk6816,NaN,NaN,[],...,https://www.reddit.com/r/books/comments/1jkxhc...,NaN,[],None,False,6,2025-03-27T06:16:08+00:00,I saw an ad for a book club that was around $5...,NaN,NaN
66,"{'is_edited': True, 'retrieved_2nd_on': 174338...",[],False,None,None,False,1000andonenites,NaN,NaN,[],...,https://www.reddit.com/r/books/comments/1jmltz...,NaN,[],None,False,6,2025-03-29T13:04:16+00:00,Laura Ingalls Wilder succeeded in her mission ...,NaN,NaN
67,"{'removal_type': 'moderator', 'retrieved_2nd_o...",[],False,None,None,False,SkeletonLordDimy,NaN,NaN,[],...,https://www.reddit.com/r/books/comments/1jmmgp...,NaN,[],None,False,6,2025-03-29T13:37:59+00:00,[removed],NaN,NaN
68,{'retrieved_2nd_on': 1743520061},[],False,None,None,False,gatheringground,NaN,NaN,[],...,https://www.reddit.com/r/books/comments/1jntr0...,NaN,[],None,False,6,2025-03-31T03:05:30+00:00,NaN,NaN,NaN
69,"{'is_edited': True, 'retrieved_2nd_on': 174358...",[],False,None,None,False,dioscurideux,NaN,NaN,[],...,https://www.reddit.com/r/books/comments/1jocx8...,NaN,[],None,False,6,2025-03-31T20:14:59+00:00,I recently finished reading/listening to Octav...,NaN,NaN

,_meta,all_awardings,approved_at_utc,approved_by,archived,associated_award,author,author_flair_background_color,author_flair_css_class,author_flair_richtext,...,top_awarded_type,total_awards_received,treatment_tags,unrepliable_reason,updated_on,ups,user_reports,created_datetime,author_cakeday,editable
0,{'retrieved_2nd_on': 1735974084},[],None,None,False,None,sedatedlife,NaN,NaN,[],...,None,0,[],None,1735844506,284,[],2025-01-02T19:01:16+00:00,NaN,NaN
1,{'retrieved_2nd_on': 1735974158},[],None,None,False,None,AvengedTenfold,NaN,NaN,[],...,None,0,[],None,1735844580,57,[],2025-01-02T19:02:30+00:00,NaN,NaN
2,{'retrieved_2nd_on': 1735975238},[],None,None,False,None,Sapphire_Bombay,NaN,NaN,[],...,None,0,[],None,1735845660,524,[],2025-01-02T19:20:30+00:00,NaN,NaN
3,{'retrieved_2nd_on': 1735975417},[],None,None,False,None,Uptons_BJs,NaN,NaN,[],...,None,0,[],None,1735845834,2,[],2025-01-02T19:23:23+00:00,NaN,NaN
4,{'retrieved_2nd_on': 1735975620},[],None,None,False,None,raseeleaamlover,NaN,NaN,[],...,None,0,[],None,1735846038,1,[],2025-01-02T19:26:47+00:00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2095,{'retrieved_2nd_on': 1743584545},[],None,None,False,None,uggghhhggghhh,NaN,NaN,[],...,None,0,[],None,1743454961,-2,[],2025-03-31T21:02:11+00:00,NaN,NaN
2096,{'retrieved_2nd_on': 1743584555},[],None,None,False,None,squid-toes,NaN,NaN,[],...,None,0,[],None,1743454972,1,[],2025-03-31T21:02:22+00:00,NaN,NaN
2097,{'retrieved_2nd_on': 1743584913},[],None,None,False,None,Paenitencia,NaN,NaN,[],...,None,0,[],None,1743455336,53,[],2025-03-31T21:08:25+00:00,NaN,NaN
2098,{'retrieved_2nd_on': 1743584937},[],None,None,False,None,rodneedermeyer,NaN,NaN,[],...,None,0,[],None,1743455357,1,[],2025-03-31T21:08:46+00:00,NaN,NaN
2099,{'retrieved_2nd_on': 1743584997},[],None,None,False,None,BoxPuns,NaN,NaN,[],...,None,0,[],None,1743455420,2,[],2025-03-31T21:09:50+00:00,NaN,NaN

In [3]:
lista_datos = [datos_submissions, datos_comments]

histograma(lista_datos, 'created_datetime')