In [1]:
import pandas as pd
from funciones_estadisticos import *

In [2]:
datos_submissions, datos_comments = separar_dataframes('ejemplo_subreddit_space.json')

display(datos_submissions)
display(datos_comments)

,_meta,all_awardings,allow_live_comments,approved_at_utc,approved_by,archived,author,author_flair_background_color,author_flair_css_class,author_flair_richtext,...,url_overridden_by_dest,user_reports,view_count,visited,wls,created_datetime,gallery_data,is_gallery,media_metadata,previous_selftext
0,"{'removal_type': 'moderator', 'retrieved_2nd_o...",[],False,None,None,False,ScienceMovies,NaN,None,[],...,https://www.cbsnews.com/news/nasa-scientists-d...,[],None,False,6,2025-01-01T02:06:32+00:00,NaN,NaN,NaN,NaN
1,"{'removal_type': 'moderator', 'retrieved_2nd_o...",[],False,None,None,False,amesinsnow,NaN,None,[],...,NaN,[],None,False,6,2025-01-01T06:09:02+00:00,NaN,NaN,NaN,NaN
2,{'retrieved_2nd_on': 1735925026},[],False,None,None,False,astro_pettit,#ea0027,None,[],...,https://i.redd.it/rlq8hobqmiae1.jpeg,[],None,False,6,2025-01-02T05:23:31+00:00,NaN,NaN,NaN,NaN
3,"{'removal_type': 'moderator', 'retrieved_2nd_o...",[],False,None,None,False,TheTelegraph,NaN,None,[],...,https://www.telegraph.co.uk/world-news/2025/01...,[],None,False,6,2025-01-03T11:23:30+00:00,NaN,NaN,NaN,NaN
4,"{'removal_type': 'moderator', 'retrieved_2nd_o...",[],False,None,None,False,Void1992,NaN,None,[],...,NaN,[],None,False,6,2025-01-03T15:47:36+00:00,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,"{'removal_type': 'moderator', 'retrieved_2nd_o...",[],False,None,None,False,MrJackDog,NaN,None,[],...,https://i.redd.it/uhvmt10pyude1.gif,[],None,False,6,2025-01-19T02:03:11+00:00,NaN,NaN,NaN,NaN
66,{'retrieved_2nd_on': 1737413827},[],False,None,None,False,Affinity_182,NaN,None,[],...,https://i.redd.it/6kukz0nxlxde1.jpeg,[],None,False,6,2025-01-19T10:56:59+00:00,NaN,NaN,NaN,NaN
67,"{'removal_type': 'moderator', 'retrieved_2nd_o...",[],False,None,None,False,Confident-Bowler1451,NaN,None,[],...,NaN,[],None,False,6,2025-01-19T14:58:34+00:00,NaN,NaN,NaN,I love space and the universe itself and do a ...
68,{'retrieved_2nd_on': 1737429223},[],False,None,None,False,firefly-metaverse,NaN,None,[],...,https://i.redd.it/lq6x622lvyde1.png,[],None,False,6,2025-01-19T15:13:33+00:00,NaN,NaN,NaN,NaN
69,{'retrieved_2nd_on': 1737437929},[],False,None,None,False,Holiday_Change9387,NaN,None,[],...,https://i.redd.it/2v7yrgsclzde1.gif,[],None,False,6,2025-01-19T17:38:42+00:00,NaN,NaN,NaN,NaN

,_meta,all_awardings,approved_at_utc,approved_by,archived,associated_award,author,author_flair_background_color,author_flair_css_class,author_flair_template_id,...,ups,user_reports,created_datetime,author_flair_richtext,author_flair_type,author_fullname,author_patreon_flair,author_premium,author_cakeday,editable
0,{'retrieved_2nd_on': 1735827275},[],None,None,False,None,[deleted],,None,NaN,...,1,[],2025-01-01T02:14:27+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,{'retrieved_2nd_on': 1735829521},[],None,None,False,None,engin3rd34,NaN,None,NaN,...,63,[],2025-01-01T02:51:50+00:00,[],text,t2_11igje,False,False,NaN,NaN
2,{'retrieved_2nd_on': 1735830967},[],None,None,False,None,Celemourn,NaN,None,NaN,...,186,[],2025-01-01T03:15:58+00:00,[],text,t2_e418x,False,False,NaN,NaN
3,{'retrieved_2nd_on': 1735831572},[],None,None,False,None,itsRobbie_,NaN,None,NaN,...,21,[],2025-01-01T03:26:02+00:00,[],text,t2_1p87howt,False,False,NaN,NaN
4,{'retrieved_2nd_on': 1735832340},[],None,None,False,None,TheFeshy,NaN,None,NaN,...,26,[],2025-01-01T03:38:53+00:00,[],text,t2_4d7rn,False,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3495,{'retrieved_2nd_on': 1737497307},[],None,None,False,None,RPGPC,NaN,None,NaN,...,1,[],2025-01-20T10:08:18+00:00,[],text,t2_9ydby,False,False,NaN,NaN
3496,{'retrieved_2nd_on': 1737503664},[],None,None,False,None,beauetconalafois,NaN,None,NaN,...,1,[],2025-01-20T11:54:15+00:00,[],text,t2_o3ozj,False,False,NaN,NaN
3497,{'retrieved_2nd_on': 1737519797},[],None,None,False,None,vinayd,NaN,None,NaN,...,5,[],2025-01-20T16:23:06+00:00,[],text,t2_a8nk,False,True,NaN,NaN
3498,{'retrieved_2nd_on': 1737524098},[],None,None,False,None,ZurEnArrhBatman,NaN,None,NaN,...,2,[],2025-01-20T17:34:48+00:00,[],text,t2_habxniy,False,False,NaN,NaN
3499,{'retrieved_2nd_on': 1737526560},[],None,None,False,None,NDaveT,NaN,None,NaN,...,2,[],2025-01-20T18:15:49+00:00,[],text,t2_blt6b,False,False,NaN,NaN

In [3]:
lista_datos = [datos_submissions, datos_comments]

histograma(lista_datos, 'created_datetime')